### ISSUE TITLE
Make customizable the initial position of the handle

### ISSUE THREAD

**Issue by avances123** [yomotsu/comparison-slider#1]
Hello, its possible to pass the initial offset of the handler via options object?

Thanks a lot

**Comment by yomotsu** [comment]
It's possible. sorry for the lack of docs.
You can set offset via the property.
```
const sliderInstance = new ComparisonSlider();
sliderInstance.offset = 1; // 0 to 1
```

**Comment by avances123** [comment]
Nice thanks!!!
