### ISSUE TITLE
Disable moving handler to position onClick

### ISSUE THREAD

**Issue by puresick** [yomotsu/comparison-slider#2]
Hi!

Is there any option to disable/prevent moving the slider to the position when a click event happens?

**Comment by yomotsu** [comment]
thanks for using the lib.
so far there is no way to it, cuz it uses mouse down as dragging start.
https://github.com/yomotsu/comparison-slider/blob/master/src/comparison-slider.ts#L63

**Comment by puresick** [comment]
Sure! Your lib was the easiest and most straightforward I found :)
Are you open to pull requests? I might look into a solution the next couple of days.

**Comment by yomotsu** [comment]
happy to hear that 😁
yes, PRs are welcome always.

I guess, the solution would be detecting drag start as first drag move with a threshold pixel

**Comment by puresick** [comment]
I implemented an option which, if enabled, looks if the event target of mousedown being the handle.
Just submitted the PR :)

**Comment by yomotsu** [comment]
your pr has been merged and published as a part of the lib!

**Comment by puresick** [comment]
Yeah, thank you very much! :)
